### PR TITLE
upload data

### PR DESCRIPTION
**Pull request by kexinhuang12345**

### CODE REVIEW

**Comment by kexinhuang12345** [comment]
Thanks @XinweiHe @yiweny for creating these datasets!!

@XinweiHe I processed the avito_500k_integ_test.zip successfully and uploaded both the raw and processed db.zip files into the server. Now, it can run with 
```python
from relbench.datasets.avito import AvitoDataset
data = AvitoDataset(process = False)
```
@yiweny i uploaded the raw event zip file but there are a few dataset processing bugs. Could you take a look and let me know when you finished fixing these errors? I can then upload the processed db.zip file to the server - thanks!

**Comment by XinweiHe** [comment]
Thanks @kexinhuang12345 for the feedback! Quick question: Have you tried run `python examples/gnn_link.py --dataset rel-avito --task user-ad-click` with `avito_500k_integ_test.zip`? I have consistently run into GPU oom issue with this command. If this is a problem for you as well, optionally, we can also use `avito_integ_test.zip` instead even though that dataset is significantly smaller.

**Comment by yiweny** [comment]
@kexinhuang12345 Can you upload the processed zip that I sent you? I have python3.10 on vm and python3.11 locally. I cannot reproduce the error that Rishabh encountered.(He said his version is python3.8). I think the error was due to the complex logic to handle the joins and loading of the original dataset(which seems to be obtained from a key-value store rather than a table from relational database). I am wondering if you can upload the processed data I sent you instead. So we can directly load the data.

**Comment by kexinhuang12345** [comment]
> Thanks @kexinhuang12345 for the feedback! Quick question: Have you tried run `python examples/gnn_link.py --dataset rel-avito --task user-ad-click` with `avito_500k_integ_test.zip`? I have consistently run into GPU oom issue with this command. If this is a problem for you as well, optionally, we can also use `avito_integ_test.zip` instead even though that dataset is significantly smaller.

Sounds good - let me try it out.

**Comment by kexinhuang12345** [comment]
> @kexinhuang12345 Can you upload the processed zip that I sent you? I have python3.10 on vm and python3.11 locally. I cannot reproduce the error that Rishabh and you encountered.(He said his version is python3.8). I think the error was due to the complex logic to handle the joins and loading of the original dataset(which seems to be obtained from a key-value store rather than a table from relational database). I am wondering if you can upload the processed data I sent you instead. So we can directly load the data rather than trying to fix and maintain complex code to flatten the tables. Thanks.

I see - i was uploading the event_recommendation.zip from the slack channel, is there another version? I don't seem to have access for it right now - thanks!

**Comment by yiweny** [comment]
@kexinhuang12345 my bad. I fixed the code logic and pushed it to this branch.

**Comment by kexinhuang12345** [comment]
Thanks! Now you can also run it with 

```python
from relbench.datasets.event import EventDataset
data = EventDataset()
```

**Review by rishabh-ranjan — APPROVED** [review]
lgtm! thanks!

**Pull request merged**
